### ISSUE TITLE
getting an error on pyphoon

### ISSUE THREAD

**Issue by krishnakanthpps** [dhoomakethu/panchanga-cli#1]
Hi Dhoomaketu. 

great work. Can you please help me with this error. 

[ec2-user@ip-172-31-11-244 panchanga-cli]$ sudo pip install https://github.com/dhoomakethu/pyphoon/tarball/master#egg=pyphoon-1.0
Collecting pyphoon-1.0 from https://github.com/dhoomakethu/pyphoon/tarball/master#egg=pyphoon-1.0
  Downloading https://github.com/dhoomakethu/pyphoon/tarball/master
     \ 20kB 56.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-A1m8e7/pyphoon-1.0/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-A1m8e7/pyphoon-1.0/

**Comment by krishnakanthpps** [comment]
Any idea how to resolve this?

![image](https://user-images.githubusercontent.com/4608088/34016858-7471b3b6-e149-11e7-9d01-a75d976269fc.png)

**Comment by dhoomakethu** [comment]
@krishnakanthpps I have pushed the fix and updated the readme, please feel free to give a try
