### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-111: ordinal not in range(128)

### ISSUE THREAD

**Issue by saikiran91** [dhoomakethu/panchanga-cli#2]
> ./panchanga_cli
> Traceback (most recent call last):
>   File "./panchanga_cli", line 6, in <module>
>     run_cli()
>   File "/Users/sai/Projects/panchanga/panchanga-cli/panchanga/cli/main.py", line 317, in run_cli
>     print u"\n".join(combined_dabbas)
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-111: ordinal not in range(128)
>

**Comment by saikiran91** [comment]
add `print u"\n".join(combined_dabbas).encode('utf-8')` and it worked fine.

**Comment by dhoomakethu** [comment]
@saikiran91 Are you using python2 ?
